#!/usr/bin/env python3
"""
walletsleepscore/_render.py — internal render helper called by score.sh.
Reads a JSON report from stdin and renders in the requested format.
CLI args: wallet=... network=... chain_id=... net_label=... explorer_link=...
          current_block=... last_active_block=... last_active_days_ago=...
          lifetime_txs=... overall_score=... label=... format=md|json|txt
"""
import sys, os, json

KVS = {}
for arg in sys.argv[1:]:
    if "=" in arg:
        k, v = arg.split("=", 1)
        KVS[k] = v

data = json.load(sys.stdin)
data["wallet"] = KVS.get("wallet", data.get("wallet", "?"))
data["net_label"] = KVS.get("net_label", data.get("net_label", "?"))
data["explorer_link"] = KVS.get("explorer_link", data.get("explorer_link", "#"))
data["format"] = KVS.get("format", "md")
fmt = data["format"]


def score_label(s):
    if s >= 90: return "WIDE AWAKE"
    if s >= 70: return "HEALTHY"
    if s >= 50: return "DROWSY"
    if s >= 30: return "LIGHT SLEEPER"
    if s >= 10: return "DEEP SLEEPER"
    return "COMATOSE"


if fmt == "json":
    print(json.dumps(data, indent=2))
elif fmt == "txt":
    print("walletsleepscore — Wallet activity report")
    print(f"  Wallet:        {data['wallet']}")
    print(f"  Network:       {data.get('net_label', '?')}")
    print(f"  Current block: {data.get('current_block', '?'):,}")
    print(f"  Last active:   block {data.get('last_active_block', 'none')}")
    print(f"  Lifetime txs:  {data.get('lifetime_txs', '?')}")
    print(f"  Overall:       {data.get('overall_score', '?')} / 100 ({data.get('label', '?')})")
    print()
    for m in data.get("metrics", []):
        print(f"  #{m['id']} {m['name']:24s} {m['score']:3d}/100  (w={m['weight']})  {m['detail']}")
else:
    out = []
    out.append("# walletsleepscore — Wallet activity report")
    out.append("")
    out.append(f"**Wallet:** [{data['wallet']}]({data.get('explorer_link', '#')})")
    out.append(f"**Network:** {data.get('net_label', '?')}")
    out.append(f"**Current block:** {data.get('current_block', '?'):,}")
    out.append(f"**Last active:** {'block ' + str(data.get('last_active_block')) + ' (' + str(data.get('last_active_days_ago', '?')) + ' days ago)' if data.get('last_active_block') else 'never'}")
    out.append(f"**Lifetime txs:** {data.get('lifetime_txs', '?')} outbound")
    out.append("")
    out.append(f"## Overall score: {data.get('overall_score', '?')} / 100 ({data.get('label', '?')})")
    out.append("")
    out.append(f"## Metrics ({len(data.get('metrics', []))})")
    out.append("")
    out.append("| # | Metric | Score | Weight | Detail |")
    out.append("|---|---|---:|---:|---|")
    for m in data.get("metrics", []):
        out.append(f"| {m['id']} | {m['name']} | {m['score']} | {m['weight']} | {m['detail']} |")
    out.append("")
    out.append("---")
    out.append("")
    out.append(f"Generated by [walletsleepscore](https://github.com/kehindemariam/walletsleepscore) on {data.get('net_label', 'Pharos')}.")
    print("\n".join(out))
